Repository GSM-MSG/MSG-BackEnd-V2, pull requests merged in 2022-07, with the labels that each got.

#189 🔀 컬럼이름 수정 및 필요없는 컬럼삭제
  src/Entities/AfterSchool.entity.ts
Labels: fix

#190 :bug: 디테일 버그
  src/Club/club.service.ts
  src/Entities/image.entity.ts
Labels: bug

#193 🔀 Edit/throw
  src/user/user.service.ts
Labels: feat

#194 동아리 생성 할 때 인원이 중복으로 들어가는 버그
  src/Club/club.service.ts
  src/image/image.service.ts
Labels: bug

#195 상세페이지 scope 문제
  src/Club/club.service.ts
Labels: bug

#196 🔀 Fix/my
  src/user/user.service.ts
Labels: fix
