Repository GSM-MSG/MSG-BackEnd-V2, pull requests merged in 2022-05, with the labels that each got.

#77 Fix/cancel
  src/Club/club.service.ts
Labels: bug

#78 🔀 :: Google OAuth - Mobile
  src/Club/club.service.ts
  src/Entities/User.entity.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/index.ts
  src/auth/dto/login.dto.ts
  src/auth/dto/oauthLogin.dto.ts
  src/auth/dto/register.dto.ts
  src/auth/dto/verify.dto.ts
  src/auth/dto/verifyHead.dto.ts
  src/email/email.service.spec.ts
  src/email/email.service.ts
  src/strategies/atStrategy.ts
  src/strategies/rtStrategy.ts
  src/user/user.service.ts
Labels: question, feat

#87 🐛 대소문자 실수 해결
  src/Club/club.controller.ts
  src/Club/club.service.ts
  src/Club/club.web.controller.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  src/user/user.web.controller.ts
Labels: fix

#89 🐛 Update 여러가지 실수
  Dockerfile
  src/auth/auth.service.ts
  src/strategies/rtStrategy.ts
Labels: fix

#90 🔀 술 좀 먹을게요
  src/Club/club.controller.ts
  src/Club/club.service.ts
  src/Club/club.web.controller.ts
  src/Club/dto/ClubData.dto.ts
  src/Club/dto/accept.dto.ts
  src/Club/dto/createClub.dto.ts
  src/Club/dto/editclub.dto.ts
  src/Club/dto/kickData.dto.ts
  src/Club/dto/kickuser.dto.ts
  src/Club/dto/relatedLink.dto.ts
  src/Entities/Club.entity.ts
  src/Entities/Member.entity.ts
  src/Entities/RelatedLink.entity.ts
  src/Entities/RequestJoin.entity.ts
  src/Entities/User.entity.ts
  src/Entities/image.entity.ts
  src/Entities/index.ts
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/strategies/atStrategy.ts
  src/strategies/atStrategy.web.ts
  src/strategies/rtStrategy.ts
  src/strategies/rtStrategy.web.ts
  src/types/StudentType.ts
  src/user/dto/exit.dto.ts
  src/user/dto/urlAddress.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  src/user/user.web.controller.ts
Labels: cleanup

#88 🔀 :: Refresh 전략 수정
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/strategies/rtStrategy.ts
Labels: fix

#92 🔀 :: 게스트용 동아리 디테일 정보
  src/Club/club.controller.ts
  src/Club/club.service.ts
  src/auth/auth.service.ts
  src/auth/auth.web.controller.ts
Labels: feat

#101 :fire: log삭제ㅎㅎ
  src/Club/club.service.ts
Labels: bug

#104 Feat/changedeco
  src/Club/club.controller.ts
  src/Club/club.web.controller.ts
Labels: cleanup

#108 Feat/makeafterschoolentity
  src/Entities/AfterSchool.entity.ts
  src/Entities/ClassRegistration.entity.ts
  src/Entities/User.entity.ts
Labels: cleanup, docs, feat

#113 🔀 심신미약입니다
  Dockerfile
  package-lock.json
  package.json
  src/Club/club.service.ts
  src/Entities/AfterSchool.entity.ts
  src/user/user.controller.ts
Labels: feat

#115 🔀 만들어봤습니다 AfterSchool
  package-lock.json
  package.json
  src/Club/club.module.ts
  src/afterSchool/afterSchool.controller.spec.ts
  src/afterSchool/afterSchool.controller.ts
  src/afterSchool/afterSchool.module.ts
  src/afterSchool/afterSchool.service.spec.ts
  src/afterSchool/afterSchool.service.ts
  src/afterSchool/afterSchool.web.controller.spec.ts
  src/afterSchool/afterSchool.web.controller.ts
  src/app.module.ts
Labels: feat

#120 Feat/applyafterschool
  src/afterSchool/afterSchool.controller.ts
  src/afterSchool/afterSchool.service.ts
  src/afterSchool/afterSchool.web.controller.ts
  src/afterSchool/dto/ApplyAfterSchool.dto.ts
  src/image/image.web.controller.ts
Labels: feat
