Repository GSM-MSG/MSG-BackEnd-V2, pull requests merged in 2022-06, with the labels that each got.

#126 Feat/entity
  src/Entities/AfterSchool.entity.ts
  src/Entities/DayOfWeek.entity.ts
  src/Entities/Grade.entity.ts
Labels: feat

#127 🔀 :: @gsm.hs.kr 제거하고 유저 변경하는거 원본값 유지해서 저장하게 변경
  src/auth/auth.service.ts
Labels: refactoring

#128 🔀 :: auth.service부분 일부 코드 리팩토링
  src/auth/auth.service.ts
Labels: cleanup

#133 Fix/dto
  src/Club/club.service.ts
  src/Club/dto/createClub.dto.ts
  src/Club/dto/editclub.dto.ts
  src/Club/dto/relatedLink.dto.ts
  src/Entities/Club.entity.ts
  src/Entities/RelatedLink.entity.ts
  src/Entities/index.ts
  src/guest/guest.controller.ts
  src/guest/guest.service.ts
Labels: feat

#134 :fire: 수요조사로 변경되면서 entity 수정
  src/Entities/AfterSchool.entity.ts
Labels: feat

#139 Feat/after schoolentity
  src/Club/club.service.ts
  src/Entities/AfterSchool.entity.ts
  src/Entities/Club.entity.ts
  src/Entities/RequestJoin.entity.ts
  src/Entities/User.entity.ts
  src/Entities/image.entity.ts
Labels: feat

#140 Feat/check role
  src/Club/club.service.ts
Labels: feat

#143 Feat/cascade
  src/Club/club.service.ts
  src/Club/dto/createClub.dto.ts
  src/Club/dto/editclub.dto.ts
  src/Entities/ClassRegistration.entity.ts
  src/Entities/DayOfWeek.entity.ts
  src/Entities/Grade.entity.ts
Labels: feat

#144 :memo: contact추가
  src/Club/dto/createClub.dto.ts
  src/Club/dto/editclub.dto.ts
Labels: feat

#145 Fix/create club
  src/Club/club.service.ts
Labels: feat

#146 Fix/accept
  src/Club/club.service.ts
  src/afterSchool/afterSchool.controller.ts
  src/afterSchool/afterSchool.service.ts
  src/afterSchool/afterSchool.web.controller.ts
  src/afterSchool/dto/FindData.dto.ts
Labels: bug

#155 Fix/search user
  .github/workflows/deploy.yml
  src/afterSchool/afterSchool.controller.ts
  src/afterSchool/afterSchool.service.ts
  src/user/user.service.ts
Labels: fix

#158 Refactoring/edit
  src/Club/club.service.ts
  src/Club/dto/editclub.dto.ts
Labels: refactoring

#153 Fix/apply
  .github/workflows/node.js.yml
  src/Club/club.service.ts
Labels: feat

#159 🔀 방과후파트를 삭제하였습니다
  src/Club/club.controller.ts
  src/Club/club.service.ts
  src/afterSchool/afterSchool.controller.spec.ts
  src/afterSchool/afterSchool.controller.ts
  src/afterSchool/afterSchool.module.ts
  src/afterSchool/afterSchool.service.spec.ts
  src/afterSchool/afterSchool.service.ts
  src/afterSchool/afterSchool.web.controller.spec.ts
  src/afterSchool/afterSchool.web.controller.ts
  src/afterSchool/dto/ApplyAfterSchool.dto.ts
  src/afterSchool/dto/FindData.dto.ts
  src/afterSchool/dto/listData.dto.ts
  src/app.module.ts
  src/user/user.controller.ts
Labels: chore

#160 🔀 자기 자신도 검색되는거 수정
  src/Club/club.controller.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  src/user/user.web.controller.ts
Labels: fix

#161 Feat/exception
  src/Club/club.service.ts
Labels: bug

#162 Feat/withdrawal
  src/Entities/Member.entity.ts
  src/Entities/RequestJoin.entity.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: feat

#163 Fix/create
  src/Club/club.controller.ts
  src/Club/club.service.ts
  src/Club/club.web.controller.ts
Labels: feat

#164 :sparkles: detailPage에 OTHER추가
  src/Club/club.service.ts
Labels: feat

#166 :recycle: detailPage변수
  src/Club/club.service.ts
Labels: feat

#168 🔀 :: 원래 자신 정보와 참가중인 동아리만 나오는 디테일페이지에 방과후도 추가 , 유저엔티티에 잘못 매핑되었던것 수정
  src/Entities/User.entity.ts
  src/user/user.service.ts
Labels: feat

#172 🔀 500버그 수정
  src/Entities/ClassRegistration.entity.ts
  src/Entities/User.entity.ts
  src/user/user.service.ts
Labels: fix

#174 🔀 선생님 엔티티 추가
  src/Entities/Teacher.entity.ts
Labels: feat

#176 :bug: 방과후 신청
  src/Club/club.service.ts
Labels: bug

#177 :sparkles: 이미지 저장
  src/Club/club.service.ts
  src/guest/guest.service.ts
Labels: feat

#180 🔀 부장위임 파트 리팩토링
  src/Club/club.service.ts
Labels: fix

#182 :sparkles: 예외처리
  src/Club/club.service.ts
Labels: feat

#181 🔀 지금 필요없는 컬럼 삭제
  src/Entities/AfterSchool.entity.ts
  src/Entities/ClassRegistration.entity.ts
Labels: feat

#183 🔀 :: 애플 정책 변경으로 인한 애플 로그인
  .github/workflows/deploy.yml
  .gitignore
  package.json
  src/guest/dto/appleRevoke.dto.ts
  src/guest/dto/appleSignin.dto.ts
  src/guest/dto/index.ts
  src/guest/guest.controller.ts
  src/guest/guest.module.ts
  src/guest/guest.service.ts
  src/lib/AuthKey.p8.gpg
  yarn.lock
Labels: feat

#185 🔀 Nest의 기본 테이블이름은 스네이크표기법입니다
  src/Club/club.controller.ts
  src/Entities/ClassRegistration.entity.ts
Labels: feat

#186 Fix/ghost detail page
  src/Club/club.controller.ts
  src/Club/club.service.ts
  src/Club/club.web.controller.ts
  src/Club/dto/DetailPage.dto.ts
  src/guest/guest.service.ts
  yarn.lock
Labels: bug

#187 detail에 userScope중 other의 조건을 수정
  src/Club/club.service.ts
Labels: feat

#188 🔀 엔티티들 규칙 적용
  src/Entities/Club.entity.ts
  src/Entities/Grade.entity.ts
  src/Entities/Member.entity.ts
  src/Entities/Teacher.entity.ts
  src/Entities/User.entity.ts
  src/Entities/image.entity.ts
Labels: feat
