Repository GSM-MSG/MSG-BackEnd-V2, pull requests merged in 2022-04, with the labels that each got.

#31 Feat/delete
  src/Club/club.controller.ts
  src/Club/club.service.ts
  src/Club/dto/createClub.dto.ts
  src/Entities/Club.entity.ts
  src/Entities/Member.entity.ts
  src/Entities/RelatedLink.entity.ts
  src/Entities/RequestJoin.entity.ts
  src/Entities/image.entity.ts
Labels: enhancement

#39 🔀 코드 수정
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: feat

#43 🔀 User/search
  src/Entities/Club.entity.ts
  src/Entities/RelatedLink.entity.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: feat

#45 🔀 User/exit
  src/user/dto/exit.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: feat

#46 Feat/image
  .gitignore
  image/0d9849000474e2ab6180cb8e291b4534
  image/e6a17e6b154421c86d566c86bb0c0a3a
  package-lock.json
  package.json
  src/app.module.ts
  src/image/image.controller.spec.ts
  src/image/image.controller.ts
  src/image/image.module.ts
  src/image/image.service.spec.ts
  src/image/image.service.ts
Labels: feat

#53 🐛 Hotfix
  src/app.module.ts
Labels: bug

#54 🔀 Update emailService
  package-lock.json
  package.json
  src/auth/auth.service.ts
  src/email/email.service.ts
Labels: feat

#58 🔀Swagger
  package-lock.json
  package.json
  src/Club/club.controller.ts
  src/Club/club.service.ts
  src/Club/dto/ClubData.dto.ts
  src/Club/dto/accept.dto.ts
  src/Club/dto/createClub.dto.ts
  src/Club/dto/editclub.dto.ts
  src/Club/dto/openClub.dto.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/dto/login.dto.ts
  src/auth/dto/register.dto.ts
  src/auth/dto/verify.dto.ts
  src/auth/dto/verifyHead.dto.ts
  src/check/check.controller.ts
  src/image/image.controller.ts
  src/image/image.service.ts
  src/main.ts
  src/user/dto/urlAddress.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: feat

#66 🐛 Update imageService
  src/image/image.service.ts
Labels: bug

#69 🔀 오류 수정 + 쿼리 이름이상한거 수정
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: bug

#71 🔀 제대로 나오게 설정
  src/main.ts
Labels: bug, fix

#73 🔀 15분이 빠지는게아닌 추가되서 반환
  src/auth/auth.service.ts
Labels: bug
